### ISSUE TITLE
EclipseLink: static weaving, inheritance and OSGi

### ISSUE THREAD

**Issue by PavelTurk** [craigday/eclipselink-staticweave-maven-plugin#10]
I use eclipselink 2.6.3. And I have two classes:

```
@Entity
class ClassA extends ClassB{...}

@MappedSuperclass
class ClassB{...}
```

And I do static weaving using maven-plugin:

```
       <plugin>
           <groupId>de.empulse.eclipselink</groupId>
           <artifactId>staticweave-maven-plugin</artifactId>
           <version>1.0.0</version>
           <executions>
               <execution>
                   <phase>process-classes</phase>
                   <goals>
                       <goal>weave</goal>
                   </goals>
                   <configuration>
                       <persistenceXMLLocation>META-INF/persistence.xml</persistenceXMLLocation>
                       <logLevel>ALL</logLevel>
                   </configuration>
               </execution>
           </executions>
           <dependencies>
               <dependency>
                   <groupId>org.eclipse.persistence</groupId>
                   <artifactId>org.eclipse.persistence.jpa</artifactId>
                   <version>${eclipselink.version}</version>
               </dependency>
           </dependencies>
       </plugin>
```

When ClassA and ClassB are in the same bundle weaving works. However, when they are in different bundles weaving doesn't work (although I added this plugin to both bundles). The developers of the plugin I use say that this plugin is heavily based of your plugin. That's why I ask this question here. Can you help me to fix this problem?

**Comment by craigday** [comment]
The plugin is a very simple wrapper around org.eclipse.persistence.tools.weaving.jpa.StaticWeaveProcessor which is native to the Eclipselink project. From what I understand it forms the basis of their Ant task to perform weaving. Perhaps you can reproduce the issue with the Ant task and raise it with Eclipselink. Cheers. Craig.

**Comment by PavelTurk** [comment]
Thank you very much for your help. Now, at least, I know where to start from.
